"""
Data Model Report Generator.

Generates a comprehensive data model report showing source tables,
target tables, columns, data types, and column-level lineage
extracted from the parsed SSIS package.

This is a deterministic generator - no LLM is needed.
"""
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from src.logging import get_logger, LogContext
from src.parsers import Mapping, Transformation, Workflow

logger = get_logger(__name__)


@dataclass
class DataModelResult:
    """Result of data model report generation."""
    success: bool
    files: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)


class DataModelReportGenerator:
    """
    Generates a data model report from a parsed SSIS workflow.

    Extracts:
    - Source tables with columns, data types, and connection info
    - Target tables with columns, data types, and connection info
    - Transformation column lineage (source column → transformation → target column)
    - Data type mappings (SSIS → PySpark)
    """

    # SSIS data type to PySpark type mapping
    SSIS_TO_PYSPARK = {
        "bool": "BooleanType",
        "i1": "ByteType",
        "i2": "ShortType",
        "i4": "IntegerType",
        "i8": "LongType",
        "r4": "FloatType",
        "r8": "DoubleType",
        "numeric": "DecimalType",
        "cy": "DecimalType",
        "wstr": "StringType",
        "str": "StringType",
        "bytes": "BinaryType",
        "dbDate": "DateType",
        "dbTime": "TimestampType",
        "dbTimeStamp": "TimestampType",
        "dbTimeStamp2": "TimestampType",
        "guid": "StringType",
        "image": "BinaryType",
        "text": "StringType",
        "ntext": "StringType",
    }

    def __init__(self, verbose: bool = False):
        self.verbose = verbose

    def generate(self, workflow: Workflow, output_dir: Path) -> DataModelResult:
        """
        Generate data model report for the workflow.

        Args:
            workflow: Parsed SSIS package
            output_dir: Directory to write the report

        Returns:
            DataModelResult with file paths and any errors
        """
        result = DataModelResult(success=True)
        output_dir.mkdir(parents=True, exist_ok=True)

        with LogContext(workflow=workflow.name):
            logger.info("Generating data model report", workflow=workflow.name)

            try:
                report = self._build_report(workflow)

                filename = self._sanitize_filename(workflow.name) + "_data_model.md"
                file_path = output_dir / filename
                file_path.write_text(report, encoding="utf-8")
                result.files.append(str(file_path))

                logger.info("Data model report generated", file=str(file_path))
            except Exception as e:
                result.success = False
                result.errors.append(f"Error generating data model report: {e}")
                logger.error("Failed to generate data model report", error=str(e))

        return result

    # ─── Report Builder ───────────────────────────────────────────

    def _build_report(self, workflow: Workflow) -> str:
        """Build the complete data model report as Markdown."""
        sections = []

        # Title
        sections.append(f"# Data Model Report — {workflow.name}\n")
        sections.append(
            f"> Auto-generated by SSIS to PySpark Migration Accelerator\n"
        )

        # Summary
        sections.append(self._build_summary(workflow))

        # Source Tables
        sections.append(self._build_source_tables(workflow))

        # Target Tables
        sections.append(self._build_target_tables(workflow))

        # Column Lineage per Mapping
        sections.append(self._build_column_lineage(workflow))

        # Data Type Mapping Reference
        sections.append(self._build_type_mapping_reference(workflow))

        return "\n".join(sections)

    # ─── Summary ──────────────────────────────────────────────────

    def _build_summary(self, workflow: Workflow) -> str:
        """Build summary section."""
        lines = ["## Summary\n"]
        lines.append(f"| Metric | Count |")
        lines.append(f"|---|---|")
        lines.append(f"| Data Flow Tasks (Mappings) | {len(workflow.mappings)} |")
        lines.append(f"| Source Tables/Queries | {len(workflow.sources)} |")
        lines.append(f"| Target Tables | {len(workflow.targets)} |")
        lines.append(f"| Transformations | {len(workflow.transformations)} |")

        if hasattr(workflow, "connection_managers") and workflow.connection_managers:
            lines.append(f"| Connection Managers | {len(workflow.connection_managers)} |")

        lines.append("")
        return "\n".join(lines)

    # ─── Source Tables ────────────────────────────────────────────

    def _build_source_tables(self, workflow: Workflow) -> str:
        """Build source tables section with columns and data types."""
        lines = ["## Source Tables\n"]

        if not workflow.sources:
            lines.append("_No source tables found._\n")
            return "\n".join(lines)

        for src in workflow.sources:
            lines.append(f"### {src.name}\n")

            if src.connection_manager:
                lines.append(f"- **Connection:** `{src.connection_manager}`")
            if src.sql_query:
                # Truncate very long queries
                query_display = src.sql_query.strip()
                if len(query_display) > 300:
                    query_display = query_display[:300] + "..."
                lines.append(f"- **SQL Query:**")
                lines.append(f"  ```sql\n  {query_display}\n  ```")

            if src.fields:
                lines.append("")
                lines.append("| # | Column Name | SSIS Data Type | PySpark Type | Length | Precision | Scale |")
                lines.append("|---|---|---|---|---|---|---|")
                for i, fld in enumerate(src.fields, 1):
                    pyspark_type = self.SSIS_TO_PYSPARK.get(fld.datatype, fld.datatype or "—")
                    lines.append(
                        f"| {i} | `{fld.name}` | `{fld.datatype or '—'}` | `{pyspark_type}` "
                        f"| {fld.length or '—'} | {fld.precision or '—'} | {fld.scale or '—'} |"
                    )
            else:
                lines.append("_No columns extracted._")

            lines.append("")

        return "\n".join(lines)

    # ─── Target Tables ────────────────────────────────────────────

    def _build_target_tables(self, workflow: Workflow) -> str:
        """Build target tables section with columns and data types."""
        lines = ["## Target Tables\n"]

        if not workflow.targets:
            lines.append("_No target tables found._\n")
            return "\n".join(lines)

        for tgt in workflow.targets:
            lines.append(f"### {tgt.name}\n")

            if tgt.connection_manager:
                lines.append(f"- **Connection:** `{tgt.connection_manager}`")

            if tgt.fields:
                lines.append("")
                lines.append("| # | Column Name | SSIS Data Type | PySpark Type | Direction |")
                lines.append("|---|---|---|---|---|")
                for i, fld in enumerate(tgt.fields, 1):
                    pyspark_type = self.SSIS_TO_PYSPARK.get(fld.datatype, fld.datatype or "—")
                    lines.append(
                        f"| {i} | `{fld.name}` | `{fld.datatype or '—'}` | `{pyspark_type}` "
                        f"| {fld.port_type} |"
                    )
            else:
                lines.append("_No columns extracted._")

            lines.append("")

        return "\n".join(lines)

    # ─── Column Lineage ───────────────────────────────────────────

    def _build_column_lineage(self, workflow: Workflow) -> str:
        """Build column lineage section showing source → transformation → target flow."""
        lines = ["## Column Lineage by Data Flow Task\n"]

        for mapping in workflow.mappings:
            lines.append(f"### {mapping.name}\n")

            if mapping.description:
                lines.append(f"_{mapping.description}_\n")

            # Sources for this mapping
            if mapping.sources:
                lines.append("**Sources:**")
                for src in mapping.sources:
                    col_names = ", ".join([f"`{f.name}`" for f in src.fields[:10]])
                    extra = f" + {len(src.fields) - 10} more" if len(src.fields) > 10 else ""
                    lines.append(f"- `{src.name}` → {col_names}{extra}")
                lines.append("")

            # Transformations for this mapping
            if mapping.transformations:
                lines.append("**Transformations:**\n")
                lines.append("| # | Component | Type | Input Columns | Output Columns | Expression / Logic |")
                lines.append("|---|---|---|---|---|---|")
                for i, tx in enumerate(mapping.transformations, 1):
                    input_cols = [f.name for f in tx.fields if f.port_type == "INPUT"]
                    output_cols = [f.name for f in tx.fields if f.port_type == "OUTPUT"]

                    in_display = ", ".join(input_cols[:5])
                    if len(input_cols) > 5:
                        in_display += f" +{len(input_cols) - 5}"

                    out_display = ", ".join(output_cols[:5])
                    if len(output_cols) > 5:
                        out_display += f" +{len(output_cols) - 5}"

                    # Extract key expression/logic
                    logic = self._get_transformation_logic(tx)

                    lines.append(
                        f"| {i} | `{tx.name}` | {tx.type} | {in_display or '—'} "
                        f"| {out_display or '—'} | {logic} |"
                    )
                lines.append("")

            # Targets for this mapping
            if mapping.targets:
                lines.append("**Targets:**")
                for tgt in mapping.targets:
                    col_names = ", ".join([f"`{f.name}`" for f in tgt.fields[:10]])
                    extra = f" + {len(tgt.fields) - 10} more" if len(tgt.fields) > 10 else ""
                    lines.append(f"- `{tgt.name}` ← {col_names}{extra}")
                lines.append("")

            # Visual data flow
            lines.append(self._build_data_flow_diagram(mapping))
            lines.append("")

        return "\n".join(lines)

    def _get_transformation_logic(self, tx: Transformation) -> str:
        """Extract a brief description of the transformation logic."""
        if tx.expression_code:
            # Truncate long expressions
            expr = tx.expression_code.replace("\n", "; ").strip()
            if len(expr) > 80:
                expr = expr[:77] + "..."
            return f"`{expr}`"
        if tx.lookup_condition:
            return f"Lookup: `{tx.lookup_condition}`"
        if tx.filter_condition:
            return f"Filter: `{tx.filter_condition}`"
        if tx.sql_query:
            q = tx.sql_query.strip()[:60]
            return f"SQL: `{q}...`"
        if tx.group_by:
            return f"Group By: {', '.join(tx.group_by)}"
        return "—"

    def _build_data_flow_diagram(self, mapping: Mapping) -> str:
        """Build a simple text-based data flow diagram for a mapping."""
        lines = ["**Data Flow:**\n```"]

        # Sources
        src_names = [s.name for s in mapping.sources]
        for s in src_names:
            lines.append(f"  [{s}]  (Source)")

        if src_names:
            lines.append("        │")
            lines.append("        ▼")

        # Transformations in execution order
        try:
            ordered = mapping.get_execution_order()
        except Exception:
            ordered = mapping.transformations

        for tx in ordered:
            lines.append(f"  [{tx.name}]  ({tx.type})")
            lines.append("        │")
            lines.append("        ▼")

        # Targets
        tgt_names = [t.name for t in mapping.targets]
        for t in tgt_names:
            lines.append(f"  [{t}]  (Target)")

        lines.append("```")
        return "\n".join(lines)

    # ─── Data Type Mapping Reference ──────────────────────────────

    def _build_type_mapping_reference(self, workflow: Workflow) -> str:
        """Build a reference table of SSIS data types used and their PySpark equivalents."""
        lines = ["## Data Type Mapping Reference\n"]

        # Collect all unique data types used across the workflow
        used_types = set()
        for src in workflow.sources:
            for f in src.fields:
                if f.datatype:
                    used_types.add(f.datatype)
        for tgt in workflow.targets:
            for f in tgt.fields:
                if f.datatype:
                    used_types.add(f.datatype)
        for m in workflow.mappings:
            for tx in m.transformations:
                for f in tx.fields:
                    if f.datatype:
                        used_types.add(f.datatype)

        if not used_types:
            lines.append("_No data types extracted._\n")
            return "\n".join(lines)

        lines.append("| SSIS Data Type | PySpark Equivalent | Usage Count |")
        lines.append("|---|---|---|")

        # Count usage per type
        type_counts: dict[str, int] = {}
        for src in workflow.sources:
            for f in src.fields:
                if f.datatype:
                    type_counts[f.datatype] = type_counts.get(f.datatype, 0) + 1
        for tgt in workflow.targets:
            for f in tgt.fields:
                if f.datatype:
                    type_counts[f.datatype] = type_counts.get(f.datatype, 0) + 1
        for m in workflow.mappings:
            for tx in m.transformations:
                for f in tx.fields:
                    if f.datatype:
                        type_counts[f.datatype] = type_counts.get(f.datatype, 0) + 1

        for dtype in sorted(used_types):
            pyspark_type = self.SSIS_TO_PYSPARK.get(dtype, "Unknown")
            count = type_counts.get(dtype, 0)
            lines.append(f"| `{dtype}` | `{pyspark_type}` | {count} |")

        lines.append("")
        return "\n".join(lines)

    # ─── Helpers ──────────────────────────────────────────────────

    def _sanitize_filename(self, name: str) -> str:
        """Convert name to valid filename."""
        sanitized = "".join(c if c.isalnum() else "_" for c in name)
        while "__" in sanitized:
            sanitized = sanitized.replace("__", "_")
        sanitized = sanitized.strip("_").lower()
        if sanitized and sanitized[0].isdigit():
            sanitized = "wf_" + sanitized
        return sanitized
