"""
utils.py — SSIS Function Equivalents for PySpark

Production-grade utility library providing PySpark-native equivalents
for all common SSIS expression functions.

Auto-generated by SSIS-to-PySpark Migration Accelerator v2.0.
"""
from __future__ import annotations

import re
from typing import Any, List, Optional

from pyspark.sql import DataFrame
from pyspark.sql import functions as F
from pyspark.sql.column import Column
from pyspark.sql.types import (
    BooleanType, ByteType, DateType, DecimalType, DoubleType,
    FloatType, IntegerType, LongType, ShortType, StringType,
    TimestampType,
)

# =============================================================================
# Conditional Expressions
# =============================================================================

def iif(condition: Column, true_value: Any, false_value: Any) -> Column:
    """SSIS IIF(condition, true, false) equivalent."""
    return F.when(condition, true_value).otherwise(false_value)


def decode(col: Column, *args) -> Column:
    """SSIS multi-value mapping — equivalent to DECODE or CASE WHEN.

    Usage: decode(F.col("status"), "A", "Active", "I", "Inactive", "Unknown")
    """
    result = None
    i = 0
    while i < len(args) - 1:
        if result is None:
            result = F.when(col == args[i], args[i + 1])
        else:
            result = result.when(col == args[i], args[i + 1])
        i += 2
    default = args[-1] if len(args) % 2 == 1 else None
    return result.otherwise(default) if result else F.lit(default)


# =============================================================================
# NULL Handling
# =============================================================================

def nvl(col: Column, default_value: Any) -> Column:
    """SSIS ISNULL / REPLACENULL equivalent."""
    return F.coalesce(col, F.lit(default_value))


def nvl2(col: Column, not_null_value: Any, null_value: Any) -> Column:
    """Return not_null_value if col is not null, else null_value."""
    return F.when(col.isNotNull(), not_null_value).otherwise(null_value)


def is_null(col: Column) -> Column:
    """SSIS ISNULL() equivalent."""
    return col.isNull()


def is_not_null(col: Column) -> Column:
    return col.isNotNull()


def null_if(col: Column, null_value: Any) -> Column:
    """Return NULL if col == null_value, else col."""
    return F.when(col == F.lit(null_value), F.lit(None)).otherwise(col)


# =============================================================================
# String Functions
# =============================================================================

def trim_chars(col: Column, chars: str = " ") -> Column:
    """SSIS TRIM() — trims leading and trailing characters."""
    if chars == " ":
        return F.trim(col)
    return F.regexp_replace(F.regexp_replace(col, f"^[{re.escape(chars)}]+", ""),
                             f"[{re.escape(chars)}]+$", "")


def ltrim_chars(col: Column, chars: str = " ") -> Column:
    if chars == " ":
        return F.ltrim(col)
    return F.regexp_replace(col, f"^[{re.escape(chars)}]+", "")


def rtrim_chars(col: Column, chars: str = " ") -> Column:
    if chars == " ":
        return F.rtrim(col)
    return F.regexp_replace(col, f"[{re.escape(chars)}]+$", "")


def findstring(col: Column, search_str: str, start: int = 1) -> Column:
    """SSIS FINDSTRING(col, pattern, occurrence) — 1-based index, 0 if not found."""
    return F.locate(search_str, col, start)


def substr(col: Column, start: int, length: Optional[int] = None) -> Column:
    """SSIS SUBSTRING(col, start, length) — 1-based."""
    if length is not None:
        return F.substring(col, start, length)
    return F.substring(col, start, 1_000_000)


def token(col: Column, delimiter: str, occurrence: int) -> Column:
    """SSIS TOKEN(col, delimiter, occurrence) — 1-based occurrence."""
    return F.split(col, re.escape(delimiter)).getItem(occurrence - 1)


def token_count(col: Column, delimiter: str) -> Column:
    """SSIS TOKENCOUNT(col, delimiter)."""
    return F.size(F.split(col, re.escape(delimiter)))


def codepoint(col: Column) -> Column:
    """SSIS CODEPOINT(col) — Unicode code point of first character."""
    return F.ascii(col)


def lpad_zeros(col: Column, length: int) -> Column:
    """Left-pad with zeros (common SSIS pattern for code fields)."""
    return F.lpad(col, length, "0")


def standardize_code(col: Column, target_length: int, pad_char: str = "0") -> Column:
    """Strip non-alphanumeric chars and pad to target_length.
    
    Equivalent to SSIS pattern:
      RIGHT(REPEAT('0', n) + REPLACE(REPLACE(TRIM(col), '-', ''), ' ', ''), n)
    """
    cleaned = F.regexp_replace(F.trim(col), r"[-\s*]", "")
    return F.lpad(cleaned, target_length, pad_char)


# =============================================================================
# Date / Time Functions
# =============================================================================

def sysdate() -> Column:
    """SSIS GETDATE() equivalent."""
    return F.current_timestamp()


def current_date_ssis() -> Column:
    """Return current date (date only, no time)."""
    return F.current_date()


def to_date_ssis(col: Column, fmt: str = "MM/dd/yyyy") -> Column:
    """SSIS date conversion — converts common SSIS date format strings."""
    spark_fmt = (fmt
                 .replace("YYYY", "yyyy").replace("DD", "dd")
                 .replace("HH24", "HH").replace("MI", "mm").replace("SS", "ss"))
    return F.to_date(col, spark_fmt)


def datepart(part: str, col: Column) -> Column:
    """SSIS DATEPART(part, col) equivalent."""
    part_lower = part.lower()
    mapping = {
        "year": F.year, "yyyy": F.year, "yy": F.year,
        "month": F.month, "mm": F.month, "m": F.month,
        "day": F.dayofmonth, "dd": F.dayofmonth, "d": F.dayofmonth,
        "hour": F.hour, "hh": F.hour,
        "minute": F.minute, "mi": F.minute, "n": F.minute,
        "second": F.second, "ss": F.second, "s": F.second,
        "weekday": F.dayofweek, "dw": F.dayofweek,
        "week": F.weekofyear, "wk": F.weekofyear,
    }
    func = mapping.get(part_lower)
    if func:
        return func(col)
    raise ValueError(f"Unsupported DATEPART: {part}")


def datediff_ssis(part: str, start_col: Column, end_col: Column) -> Column:
    """SSIS DATEDIFF(part, start, end) equivalent."""
    part_lower = part.lower()
    if part_lower in ("day", "dd", "d"):
        return F.datediff(end_col, start_col)
    if part_lower in ("month", "mm", "m"):
        return F.months_between(end_col, start_col).cast("int")
    if part_lower in ("year", "yyyy", "yy"):
        return (F.year(end_col) - F.year(start_col))
    raise ValueError(f"Unsupported DATEDIFF part: {part}")


def dateadd_ssis(part: str, amount: Any, col: Column) -> Column:
    """SSIS DATEADD(part, amount, col) equivalent."""
    part_lower = part.lower()
    if part_lower in ("day", "dd", "d"):
        return F.date_add(col, amount)
    if part_lower in ("month", "mm", "m"):
        return F.add_months(col, amount)
    if part_lower in ("year", "yyyy", "yy"):
        return F.add_months(col, amount * 12)
    raise ValueError(f"Unsupported DATEADD part: {part}")


# =============================================================================
# Lookup Helper
# =============================================================================

def lookup(
    source_df: DataFrame,
    lookup_df: DataFrame,
    condition: Column,
    lookup_columns: List[str],
    default_values: Optional[dict] = None,
    broadcast: bool = True,
) -> DataFrame:
    """SSIS Lookup transformation equivalent.

    Args:
        source_df: Source DataFrame
        lookup_df: Reference DataFrame
        condition: Join condition column expression
        lookup_columns: Columns to bring in from lookup
        default_values: Dict of {col_name: default_val} for no-match rows
        broadcast: Whether to broadcast the lookup table (True for < 10MB)
    """
    lookup_selected = lookup_df.select(*lookup_columns)
    ref = F.broadcast(lookup_selected) if broadcast else lookup_selected
    result = source_df.join(ref, condition, "left")
    if default_values:
        for col_name, default_val in default_values.items():
            result = result.withColumn(
                col_name, F.coalesce(F.col(col_name), F.lit(default_val)))
    return result


# =============================================================================
# Aggregation Helper
# =============================================================================

def aggregate_with_groups(
    df: DataFrame,
    group_by_cols: List[str],
    aggregations: dict,
) -> DataFrame:
    """SSIS Aggregate transformation equivalent.

    Args:
        df: Input DataFrame
        group_by_cols: GROUP BY columns
        aggregations: Dict of {output_col: (agg_func_str, input_col)}
    """
    agg_map = {
        "sum": F.sum, "count": F.count, "avg": F.avg,
        "min": F.min, "max": F.max,
        "count_distinct": F.countDistinct,
        "first": F.first, "last": F.last,
    }
    agg_exprs = [
        agg_map[func.lower()](in_col).alias(out_col)
        for out_col, (func, in_col) in aggregations.items()
        if func.lower() in agg_map
    ]
    return df.groupBy(*group_by_cols).agg(*agg_exprs)


# =============================================================================
# SSIS Error Code Table  (used by Script Components that call GetErrorDescription)
# =============================================================================

_SSIS_ERROR_CODES: dict[int, str] = {
    -1071607685: "The value violated the integrity constraints for the column",
    -1071607682: "Data truncation occurred",
    -1071607449: "Lookup returned no rows for this row",
    -1071607446: "A NULL value cannot be inserted into a non-nullable column",
    -1071600000: "An error occurred while evaluating the expression",
    -1071628845: "Conversion failed because the data value overflowed the type",
    -1071607683: "Conversion from type to DT_WSTR is not supported",
    -1071636471: "An OLE DB error has occurred",
    -1071607712: "The column data type is not supported",
    -1071607709: "The component could not determine the metadata at design time",
    -1071616456: "There was an error with the script command text",
    -1071611876: "The specified object was not found",
}


def resolve_error_descriptions(df: DataFrame) -> DataFrame:
    """SSIS SC_GetErrorDescription Script Component equivalent.
    
    Translates integer ErrorCode values to human-readable strings.
    """
    error_map_expr = F.create_map(
        *[item for code, desc in _SSIS_ERROR_CODES.items()
          for item in (F.lit(code), F.lit(desc))]
    )
    return df.withColumn(
        "ErrorDescription",
        F.when(
            F.col("ErrorCode").isNotNull(),
            F.coalesce(
                error_map_expr[F.col("ErrorCode").cast("int")],
                F.concat(F.lit("SSIS error code: "), F.col("ErrorCode").cast("string")),
            ),
        ).otherwise(F.col("ErrorDescription")),
    )
