# =============================================================================
# AUTO-GENERATED by SSIS-to-PySpark Rule Engine
# Package   : HealthcareETL
# Layer     : Silver
# Generated : 2026-02-17 14:27:03
#
# Data Lineage:
#   Bronze Sources : bronze.member, bronze.claims_837, bronze.pbm_pharmacy
#   Silver Targets : silver.member_transformed, silver.claims_transformed,
#                    silver.pharmacy_transformed
#   Gold Targets   : [GOLD — NOT implemented here]
#
# Execution Order (Precedence Constraints):
#   DFT_TransformMembers  ──(Success)──► DFT_TransformClaims
#                         ──(Success)──► DFT_TransformPharmacy
#   DFT_TransformClaims   ──(Success)──► [DFT_MemberClaimsAggregation — GOLD]
#   DFT_TransformPharmacy ──(Success)──► [DFT_PharmacyAggregation     — GOLD]
# =============================================================================

from __future__ import annotations

import logging
import os
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from typing import Dict, Optional

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import BooleanType, IntegerType, StringType

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s — %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("silver_healthcareetl")

# ---------------------------------------------------------------------------
# Package Variables (from SSIS DTS:Variable)
# ---------------------------------------------------------------------------
# User::ProcessingDate  [DataType=7 / Date]  — passed as runtime arg; never hardcoded
# User::RowCount_Members / Claims / Pharmacy [DataType=3 / Int32]
EXTRACT_COUNT: int = 0
ERROR_COUNT:   int = 0
LOAD_COUNT:    int = 0

# ---------------------------------------------------------------------------
# JDBC Config Builder  (Rule: Multi-CM flat dict — connection_manager_rules.md §2.8)
# ---------------------------------------------------------------------------

def build_pipeline_jdbc_config() -> dict:
    def _url(host_env: str, port_env: str, db_env: str, host_d: str, port_d: str, db_d: str) -> str:
        h = os.environ.get(host_env, host_d)
        p = os.environ.get(port_env, port_d)
        d = os.environ.get(db_env,  db_d)
        return (f"jdbc:sqlserver://{h}:{p};databaseName={d};"
                "encrypt=true;trustServerCertificate=true")

    return {
        "source_url": _url("SOURCE_DB_HOST", "SOURCE_DB_PORT", "SOURCE_DB_NAME",
                           "source-server", "1433", "SourceDB"),
        "target_url": _url("TARGET_DB_HOST", "TARGET_DB_PORT", "TARGET_DB_NAME",
                           "target-server", "1433", "TargetDB"),
        "npi_url":    _url("NPI_DB_HOST",    "NPI_DB_PORT",    "NPI_DB_NAME",
                           "target-server",  "1433", "TargetDB"),  # npi_registry lives in TargetDB
        "driver":   "com.microsoft.sqlserver.jdbc.SQLServerDriver",
        "user":     os.environ.get("ETL_DB_USER",     ""),  # TODO: dbutils.secrets.get(...)
        "password": os.environ.get("ETL_DB_PASSWORD", ""),  # TODO: dbutils.secrets.get(...)
    }


# =============================================================================
# SECTION 1 — DFT_TransformMembers
# =============================================================================

def transform_gender_standardization(input_df: DataFrame) -> DataFrame:
    try:
        norm = F.upper(F.trim(F.col("gender")))
        expr = (
            F.when(F.col("gender").isNull() | (norm == "U") | (norm == "UNKNOWN"), F.lit("U"))
             .when((norm == "M") | (norm == "MALE"),   F.lit("M"))
             .when((norm == "F") | (norm == "FEMALE"), F.lit("F"))
             .otherwise(F.lit("Other"))
        )
        return input_df.withColumn("gender_standardized", expr)
    except Exception as e:
        logger.error("transform_gender_standardization failed: %s", e, exc_info=True)
        raise


def transform_zip_code_standardization(input_df: DataFrame) -> DataFrame:
    try:
        df = input_df.withColumn(
            "_zip_cleaned",
            F.regexp_replace(F.regexp_replace(F.trim(F.col("zip_code")), "-", ""), " ", ""),
        )
        df = df.withColumn(
            "zip_code_standardized",
            F.when(
                F.length(F.col("_zip_cleaned")) == 9,
                F.concat(
                    F.substring(F.col("_zip_cleaned"), 1, 5),
                    F.lit("-"),
                    F.substring(F.col("_zip_cleaned"), 6, 4),
                ),
            ).when(
                F.length(F.col("_zip_cleaned")) >= 5,
                F.substring(F.col("_zip_cleaned"), 1, 5),
            ).otherwise(
                F.lpad(F.col("_zip_cleaned"), 5, "0"),
            ),
        ).drop("_zip_cleaned")
        return df
    except Exception as e:
        logger.error("transform_zip_code_standardization failed: %s", e, exc_info=True)
        raise


def validate_member_data(df: DataFrame) -> DataFrame:
    try:
        total = df.count()
        null_df = df.filter(F.col("member_id").isNull()).withColumn(
            "_error_reason", F.lit("member_id is NULL")
        ).withColumn("_error_timestamp", F.current_timestamp())
        null_count = null_df.count()
        if null_count > 0:
            logger.warning("validate_member_data: %d/%d rows have NULL member_id", null_count, total)
            null_df.write.mode("append").saveAsTable("error.silver_member_rejects")
        dup_count = df.groupBy("member_id").count().filter(F.col("count") > 1).count()
        if dup_count > 0:
            logger.warning("validate_member_data: %d duplicate member_id values", dup_count)
        valid_df = df.filter(F.col("member_id").isNotNull())
        logger.info("validate_member_data: %d valid / %d rejected", valid_df.count(), null_count)
        return valid_df
    except Exception as e:
        logger.error("validate_member_data failed: %s", e, exc_info=True)
        raise


def run_dft_transform_members(spark: SparkSession) -> int:
    try:
        logger.info("[DFT_TransformMembers] START")
        raw_df = spark.table("bronze.member")

        df = transform_gender_standardization(raw_df)
        df = transform_zip_code_standardization(df)
        df = validate_member_data(df)

        # Destination column projection — only SSIS-mapped columns written
        write_df = df.select(
            "member_id", "mrn", "first_name", "last_name", "date_of_birth",
            "gender", "race", "ethnicity",
            "address_line1", "city", "state", "zip_code",
            "phone", "email", "death_date",
            "created_timestamp", "updated_timestamp",
            F.col("gender_standardized"),
            F.col("zip_code_standardized"),
        )
        write_df.write.mode("overwrite").option("overwriteSchema", "true").saveAsTable(
            "silver.member_transformed"
        )
        row_count = write_df.count()
        logger.info("[DFT_TransformMembers] completed: %d rows → silver.member_transformed", row_count)
        return row_count
    except Exception as e:
        logger.error("[DFT_TransformMembers] FAILED: %s", e, exc_info=True)
        raise


# =============================================================================
# SECTION 2 — DFT_TransformClaims
# =============================================================================

def lookup_provider_npi(input_df: DataFrame, spark: SparkSession, jdbc_config: dict) -> DataFrame:
    try:
        # Rule S-LKP-1: npi_registry lives in TargetDB → use npi_url
        lookup_url = jdbc_config.get("npi_url") or jdbc_config.get("target_url", "")

        npi_sql = """(
            SELECT
                npi,
                CONCAT(
                    provider_organization_name,
                    COALESCE(CONCAT(' - ', provider_first_name, ' ', provider_last_name), '')
                ) AS provider_name_standardized,
                entity_type_code AS provider_type,
                healthcare_provider_taxonomy_code_1 AS taxonomy_code
            FROM dbo.npi_registry
            WHERE npi IS NOT NULL
        ) AS npi_ref"""

        npi_df = (
            spark.read.format("jdbc")
            .option("url",      lookup_url)
            .option("dbtable",  npi_sql)
            .option("driver",   jdbc_config["driver"])
            .option("user",     jdbc_config["user"])
            .option("password", jdbc_config["password"])
            .load()
            .cache()
        )

        npi_broadcast = F.broadcast(npi_df)

        matched_df = (
            input_df.alias("c")
            .join(npi_broadcast.alias("n"),
                  F.col("c.provider_npi").eqNullSafe(F.col("n.npi")), "inner")
            .select(
                F.col("c.*"),
                F.col("n.provider_name_standardized"),
                F.col("n.provider_type"),
                F.col("n.taxonomy_code"),
            )
        )

        unmatched_df = (
            input_df.alias("c")
            .join(npi_broadcast.alias("n"),
                  F.col("c.provider_npi").eqNullSafe(F.col("n.npi")), "left_anti")
            .withColumn("provider_name_standardized", F.lit(None).cast(StringType()))
            .withColumn("provider_type",              F.lit(None).cast(StringType()))
            .withColumn("taxonomy_code",              F.lit(None).cast(StringType()))
        )

        matched_count   = matched_df.count()
        unmatched_count = unmatched_df.count()
        logger.info("LKP_ProviderNPI: matched=%d unmatched=%d", matched_count, unmatched_count)
        if unmatched_count > 0:
            logger.warning("LKP_ProviderNPI: %d claims have no NPI registry match", unmatched_count)

        result_df = matched_df.unionByName(unmatched_df)
        npi_df.unpersist()
        return result_df
    except Exception as e:
        logger.error("lookup_provider_npi failed: %s", e, exc_info=True)
        raise


def transform_der_claim_type(input_df: DataFrame) -> DataFrame:
    try:
        cond_freq_orig    = F.col("claim_frequency") == F.lit("1")
        cond_freq_replace = F.col("claim_frequency") == F.lit("7")
        # Lexicographic CPT range — faithfully replicates SSIS string comparison
        cond_cpt = (
            (F.substring(F.col("procedure_code1"), 1, 2) >= F.lit("99")) &
            (F.substring(F.col("procedure_code1"), 1, 5) <= F.lit("99223"))
        )
        is_inpatient_expr = cond_freq_orig | cond_freq_replace | cond_cpt

        df = input_df.withColumn(
            "is_inpatient",
            F.when(is_inpatient_expr, True).otherwise(False).cast(BooleanType()),
        ).withColumn(
            "claim_year",
            F.year(F.col("service_date_start")).cast(IntegerType()),
        )
        return df
    except Exception as e:
        logger.error("transform_der_claim_type failed: %s", e, exc_info=True)
        raise


def validate_claims_data(df: DataFrame) -> DataFrame:
    try:
        total = df.count()
        null_df = df.filter(F.col("claim_id").isNull()).withColumn(
            "_error_reason", F.lit("claim_id is NULL")
        ).withColumn("_error_timestamp", F.current_timestamp())
        null_count = null_df.count()
        if null_count > 0:
            logger.warning("validate_claims_data: %d/%d rows have NULL claim_id", null_count, total)
            null_df.write.mode("append").saveAsTable("error.silver_claims_rejects")
        dup_count = df.groupBy("claim_id").count().filter(F.col("count") > 1).count()
        if dup_count > 0:
            logger.warning("validate_claims_data: %d duplicate claim_id values", dup_count)
        valid_df = df.filter(F.col("claim_id").isNotNull())
        logger.info("validate_claims_data: %d valid / %d rejected", valid_df.count(), null_count)
        return valid_df
    except Exception as e:
        logger.error("validate_claims_data failed: %s", e, exc_info=True)
        raise


# Destination columns for silver.claims_transformed (SSIS DST_ClaimsTransformed mapping)
_CLAIMS_DEST_COLS = [
    "claim_id", "member_id", "patient_control_number", "provider_npi",
    "billing_provider", "claim_status", "total_charge_amount", "paid_amount",
    "service_date_start", "service_date_end", "diagnosis_code1", "diagnosis_code2",
    "procedure_code1", "procedure_code2", "claim_frequency", "prior_auth_number",
    "created_timestamp", "updated_timestamp",
    "provider_name_standardized", "provider_type", "taxonomy_code",
    "is_inpatient", "claim_year",
]


def run_dft_transform_claims(spark: SparkSession, jdbc_config: dict) -> int:
    try:
        logger.info("[DFT_TransformClaims] START")
        raw_df = spark.table("bronze.claims_837")

        enriched_df = lookup_provider_npi(raw_df, spark, jdbc_config)
        typed_df    = transform_der_claim_type(enriched_df)
        valid_df    = validate_claims_data(typed_df)

        write_df = valid_df.select([F.col(c) for c in _CLAIMS_DEST_COLS])
        write_df.write.mode("overwrite").option("overwriteSchema", "true").saveAsTable(
            "silver.claims_transformed"
        )
        row_count = write_df.count()
        logger.info("[DFT_TransformClaims] completed: %d rows → silver.claims_transformed", row_count)
        return row_count
    except Exception as e:
        logger.error("[DFT_TransformClaims] FAILED: %s", e, exc_info=True)
        raise


# =============================================================================
# SECTION 3 — DFT_TransformPharmacy
# =============================================================================

def transform_ndc_standardization(input_df: DataFrame) -> DataFrame:
    try:
        # SSIS: RIGHT("00000000000" + REPLACE(REPLACE(REPLACE(TRIM(ndc_code),"-","")," ",""),"*",""), 11)
        cleaned = F.regexp_replace(F.trim(F.col("ndc_code")), r"[-\s*]", "")
        ndc_11  = F.lpad(cleaned, 11, "0")

        df = input_df.withColumn("ndc_code_standardized", ndc_11)
        df = df.withColumn(
            "ndc_formatted",
            F.concat(
                F.substring(F.col("ndc_code_standardized"), 1,  5), F.lit("-"),
                F.substring(F.col("ndc_code_standardized"), 6,  4), F.lit("-"),
                F.substring(F.col("ndc_code_standardized"), 10, 2),
            ),
        )
        df = df.withColumn("rx_year", F.year(F.col("fill_date")).cast(IntegerType()))
        return df
    except Exception as e:
        logger.error("transform_ndc_standardization failed: %s", e, exc_info=True)
        raise


def validate_pharmacy_data(df: DataFrame) -> DataFrame:
    try:
        total = df.count()
        null_df = df.filter(F.col("rx_claim_id").isNull()).withColumn(
            "_error_reason", F.lit("rx_claim_id is NULL")
        ).withColumn("_error_timestamp", F.current_timestamp())
        null_count = null_df.count()
        if null_count > 0:
            logger.warning("validate_pharmacy_data: %d/%d rows have NULL rx_claim_id", null_count, total)
            null_df.write.mode("append").saveAsTable("error.silver_pharmacy_rejects")
        dup_count = df.groupBy("rx_claim_id").count().filter(F.col("count") > 1).count()
        if dup_count > 0:
            logger.warning("validate_pharmacy_data: %d duplicate rx_claim_id values", dup_count)
        valid_df = df.filter(F.col("rx_claim_id").isNotNull())
        logger.info("validate_pharmacy_data: %d valid / %d rejected", valid_df.count(), null_count)
        return valid_df
    except Exception as e:
        logger.error("validate_pharmacy_data failed: %s", e, exc_info=True)
        raise


# Destination columns for silver.pharmacy_transformed (SSIS DST_PharmacyTransformed mapping)
_PHARMACY_DEST_COLS = [
    "rx_claim_id", "member_id", "rx_number", "ndc_code", "drug_name", "drug_strength",
    "quantity", "days_supply", "fill_date", "dispense_pharmacy_npi",
    "dispense_pharmacy_name", "ingredient_cost", "total_cost", "paid_amount",
    "bin", "pcin", "created_timestamp", "updated_timestamp",
    "ndc_code_standardized", "ndc_formatted", "rx_year",
]


def run_dft_transform_pharmacy(spark: SparkSession) -> int:
    try:
        logger.info("[DFT_TransformPharmacy] START")
        raw_df = spark.table("bronze.pbm_pharmacy")

        df       = transform_ndc_standardization(raw_df)
        valid_df = validate_pharmacy_data(df)

        write_df = valid_df.select([F.col(c) for c in _PHARMACY_DEST_COLS])
        write_df.write.mode("overwrite").option("overwriteSchema", "true").saveAsTable(
            "silver.pharmacy_transformed"
        )
        row_count = write_df.count()
        logger.info("[DFT_TransformPharmacy] completed: %d rows → silver.pharmacy_transformed", row_count)
        return row_count
    except Exception as e:
        logger.error("[DFT_TransformPharmacy] FAILED: %s", e, exc_info=True)
        raise


# =============================================================================
# SECTION 4 — Silver Pipeline Orchestrator
# =============================================================================

def run_silver_pipeline(
    spark: SparkSession,
    processing_date: Optional[str] = None,
    jdbc_config: Optional[dict] = None,
    task_filter: Optional[str] = None,
    batch_identifier: Optional[str] = None,
    batch_id: Optional[int] = None,
    batch_run_id: Optional[int] = None,
) -> dict:
    global EXTRACT_COUNT, ERROR_COUNT, LOAD_COUNT

    if jdbc_config is None:
        jdbc_config = build_pipeline_jdbc_config()

    start_time = datetime.now()
    logger.info("=" * 70)
    logger.info("Silver Pipeline START  processing_date=%s  filter=%s", processing_date, task_filter)
    logger.info("=" * 70)

    results: dict = {}

    # ── Phase 1: DFT_TransformMembers (must complete before claims/pharmacy) ──
    run_members  = not task_filter or "members"  in task_filter.lower()
    run_claims   = not task_filter or "claims"   in task_filter.lower()
    run_pharmacy = not task_filter or "pharmacy" in task_filter.lower()

    # Members must run first (precedence constraint)
    if run_members:
        count = run_dft_transform_members(spark)
        results["members"] = count
        EXTRACT_COUNT += count
        logger.info("User::RowCount_Members = %d", count)

    # Claims and Pharmacy can run in parallel after Members
    parallel_tasks = {}
    if run_claims:
        parallel_tasks["claims"] = lambda: run_dft_transform_claims(spark, jdbc_config)
    if run_pharmacy:
        parallel_tasks["pharmacy"] = lambda: run_dft_transform_pharmacy(spark)

    if parallel_tasks:
        with ThreadPoolExecutor(max_workers=len(parallel_tasks)) as executor:
            futures = {executor.submit(fn): name for name, fn in parallel_tasks.items()}
            for future in as_completed(futures):
                name = futures[future]
                try:
                    count = future.result()
                    results[name] = count
                    EXTRACT_COUNT += count
                    if name == "claims":
                        logger.info("User::RowCount_Claims = %d", count)
                    elif name == "pharmacy":
                        logger.info("User::RowCount_Pharmacy = %d", count)
                except Exception as exc:
                    logger.error("Phase 1 task '%s' FAILED: %s", name, exc, exc_info=True)
                    raise

    LOAD_COUNT  = EXTRACT_COUNT - ERROR_COUNT
    elapsed     = datetime.now() - start_time

    logger.info("=" * 70)
    logger.info(
        "Silver Pipeline COMPLETE  elapsed=%s  extract=%d  errors=%d  loaded=%d",
        str(elapsed), EXTRACT_COUNT, ERROR_COUNT, LOAD_COUNT,
    )
    logger.info("=" * 70)

    results.update({
        "extract_count": EXTRACT_COUNT,
        "error_count":   ERROR_COUNT,
        "load_count":    LOAD_COUNT,
    })
    return results


# =============================================================================
# Entry Point
# =============================================================================

if __name__ == "__main__":
    _spark = (
        SparkSession.builder
        .appName("HealthcareETL — Silver Layer")
        .config("spark.sql.adaptive.enabled",                    "true")
        .config("spark.sql.adaptive.coalescePartitions.enabled", "true")
        .config("spark.sql.sources.partitionOverwriteMode",      "dynamic")
        .getOrCreate()
    )
    _spark.sparkContext.setLogLevel("WARN")

    _processing_date = sys.argv[1] if len(sys.argv) > 1 else None
    _task_filter     = sys.argv[2] if len(sys.argv) > 2 else None

    try:
        run_silver_pipeline(
            spark           = _spark,
            processing_date = _processing_date,
            task_filter     = _task_filter,
        )
    except Exception:
        logger.critical("Silver pipeline terminated with errors.")
        sys.exit(1)
    finally:
        _spark.stop()